# Default values for uptime-service-payloads-scrapper.
# This is a YAML-formatted file.

# -- The number of replicas
replicaCount: 1

image:
  # -- The image repository
  repository: 673156464838.dkr.ecr.us-west-2.amazonaws.com/uptime-service-payloads-scrapper
  # -- The image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0-6e0b3ec"

# -- The secrets used to pull the image
imagePullSecrets: []
# -- The release name override
nameOverride: ""
# -- The full release name override
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  name: ""

# -- Annotations to add to the pods
podAnnotations: {}

# -- Pods Security Context
podSecurityContext: {}
  # fsGroup: 2000

# -- Security Context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- The service type
  type: ClusterIP
  # -- The service port
  port: 8080

ingress:
  # -- Whether to enable ingress
  enabled: false
  # -- Ingress class name
  className: ""
  # -- Ingress Annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress hosts
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  # -- Whether to enable autoscaling
  enabled: false
  # -- The minimum number of pods
  minReplicas: 1
  # -- The maximum number of pods
  maxReplicas: 5
  # -- The target CPU utilization percentage
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Node selector
nodeSelector: {}

# -- Tolerations
tolerations: []

# -- Affinity
affinity: {}

persistence:
  # -- Whether to enable persistence
  enabled: false
  # -- The storage class
  storageClass: ebs-gp3-encrypted
  # -- The access mode
  accessMode: ReadWriteOnce
  # -- The size of the PVC
  size: 10Gi
  # -- Annotations to add to the PVC
  annotations: {}
