---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
  labels:
    app: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  entrypoint.sh: |-
{{ (.Files.Get "scripts/entrypoint.sh") | indent 4 }}
{{- if .Values.deployment.storeBlocks.aws.enabled }}
  gsutil-impersonator.sh: |-
{{ (.Files.Get "scripts/gsutil-impersonator.sh") | indent 4 }}
  gcloud-impersonator.sh: |-
{{ (.Files.Get "scripts/gcloud-impersonator.sh") | indent 4 }}
  s3-blocks-uploader.sh: |-
{{ (.Files.Get "scripts/s3-blocks-uploader.sh") | indent 4 }}
{{- end }}
{{- if .Values.node.libp2pKeys.create }}
  generate-libp2p-keys.sh: |-
{{ (.Files.Get "scripts/generate-libp2p-keys.sh") | indent 4 }}
{{- end }}
  healthcheck.sh: |-
{{ (.Files.Get "scripts/healthcheck.sh") | indent 4 }}
