{{- if .Values.node.exposeGraphql }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graphql
  labels:
    app: {{ .Release.Name }}
    testnet: {{ .Values.deployment.testnet }}
    role: {{ default "undefined" .Values.node.role }}
  {{- with .Values.service.graphql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.graphql.type | quote }}
  {{- if .Values.service.graphql.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.graphql.loadBalancerClass | quote }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.service.graphql.publishNotReadyAddresses }}
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: graphql
    protocol: TCP
    port: {{ .Values.node.ports.graphql }}
    targetPort: {{ .Values.node.ports.graphql }}
  - name: proxy
    protocol: TCP
    port: {{ .Values.node.ports.proxy }}
    targetPort: {{ .Values.node.ports.proxy }}
{{- end }}
