apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmina-node.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "openmina-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- if .Values.persistence.enabled }}
    type: Recreate
    {{- else }}
    type: RollingUpdate
    {{- end }}
  selector:
    matchLabels:
      {{- include "openmina-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/environment: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "openmina-node.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openmina-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/openmina", "node"]
          {{- if .Values.node.args }}
          args:
            {{- toYaml .Values.node.args | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: OPENMINA_HOME
              value: {{ .Values.node.homeDirectory }}
            {{- if .Values.node.envVars }}
            {{- toYaml .Values.node.envVars | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: openmina-keys
              mountPath: {{ .Values.node.homeDirectory }}/keys
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: openmina-home
              mountPath: {{ .Values.node.homeDirectory }}
            {{ end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: openmina-keys
          secret:
            secretName: {{ include "openmina-node.fullname" . }}
            defaultMode: 0600
      {{- if .Values.persistence.enabled }}
        - name: openmina-home
          persistentVolumeClaim:
            claimName: {{ include "openmina-node.fullname" . }}
      {{ end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
