apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgt-gov-bot.fullname" . }}
data:
  discordClientId: {{ .Values.bot.config.discord.clientId | b64enc }}
  discordGuildId: {{ .Values.bot.config.discord.guildId | b64enc }}
  discordToken: {{ .Values.bot.config.discord.token | b64enc }}
