apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgt-gov-bot.fullname" . }}-ocv-web
  labels:
    {{- include "pgt-gov-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ocvWeb.service.type }}
  ports:
    - port: {{ .Values.ocvWeb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pgt-gov-bot.selectorLabels" . | nindent 4 }}
