apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mina-archive.fullname" . }}-node
  labels:
    {{- include "mina-archive.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.node.replicas }}
  {{- if gt (.Values.node.replicas | int) 1 }}
  {{- fail "Mina archive should run one process per database maximum" }}
  {{- end}}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "mina-archive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
        {{- if .Values.node.metrics.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ .Values.node.ports.metrics | quote }}
        prometheus.io/path: '/metrics'
        {{- end }}
        {{- with .Values.node.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mina-archive.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        # legacy labels backward compatible
        app: {{ include "mina-archive.fullname" . }}
        network: {{ .Values.network }}
        role: archive
    spec:
      serviceAccountName: {{ include "mina-archive.fullname" . }}
      initContainers:
        - name: archive-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bash", "/scripts/archive-command-init.sh"]
          args: []
          env:
            {{- include "pgEnvVars" . | nindent 12 }}
            - name: DB_BOOTSTRAP_LOCKING_DATABASE_NAME
              value: {{ include "bootstrapLockingDatabaseName" . }}
            - name: DB_BOOTSTRAP_TIMEOUT_SEC
              value: {{ .Values.dbBootstrap.maxExpectedDurationInSeconds | quote }}
          {{- if .Values.node.configFileUrl }}
            - name: ARCHIVE_CONFIG_FILE_URL
              value: {{ .Values.node.configFileUrl }}
          {{- end }}
          volumeMounts:
            - name: scripts
              mountPath: "/scripts/"
            - name: config
              mountPath: /config/
      containers:
        - name: archive
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - mina-archive
            - run
            - --postgres-uri
            - {{ include "postgresUri" . }}
            - --server-port
            - {{ .Values.node.ports.rpc | quote}}
          {{- if .Values.node.metrics.enabled }}
            - --metrics-port
            - {{ .Values.node.ports.metrics | quote }}
          {{- end }}
          {{- if .Values.node.configFileUrl }}
            - --config-file
            - /config/config-file.json
          {{- end }}
          {{- with .Values.node.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "pgEnvVars" . | nindent 12 }}
            - name: ARCHIVE_NODE_PORT_RPC
              value: {{ .Values.node.ports.rpc | quote }}
            {{- if .Values.node.extraEnvVars }}
            {{- toYaml .Values.node.extraEnvVars | nindent 12 }}
            {{- end }}
          ports:
            - name: rpc
              protocol: TCP
              containerPort: {{ .Values.node.ports.rpc }}
            {{- if .Values.node.metrics.enabled }}
            - name: metrics
              protocol: TCP
              containerPort: {{ .Values.node.ports.metrics }}
            {{- end }}
          {{- with .Values.node.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts/
            - name: config
              mountPath: /config/
      volumes:
        - name: scripts
          configMap:
            name: {{ include "mina-archive.fullname" . }}-scripts
            defaultMode: 0777
        - name: config
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
