---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matterbridge-bot.fullname" . }}
  labels:
    {{- include "matterbridge-bot.labels" . | nindent 4 }}
data:
  matterbridge.toml: {{ .Values.matterbridge.configTomlBase64 | toString }}
