network: mainnet
databaseName: archive
image:
  repository: minaprotocol/mina-archive
  tag: 3.0.0-93e0279-bullseye

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::673156464838:role/MinaNodesS3_sandbox

postgresql:
  enabled: true
  primary:
    resourcesPreset: "2xlarge"
    persistence:
      enabled: false
      storageClass: "ebs-gp3-encrypted"
      size: 8Gi

dbBootstrap:
  enabled: true
  createDatabase: true
  sqlFileUrls:
    - https://raw.githubusercontent.com/MinaProtocol/mina/develop/src/app/archive/create_schema.sql
  extraSqlFileUrls:
    - https://raw.githubusercontent.com/MinaProtocol/mina/develop/src/app/archive/zkapp_tables.sql

node:
  replicas: 1
  configFileUrl: http://673156464838-mina-genesis-ledgers.s3-us-west-2.amazonaws.com/mainnet/genesis_ledger.json

missingBlocksGuardian:
  enabled: true
  suspend: true
  precomputedBlocksUrl: https://673156464838-mina-precomputed-blocks.s3-us-west-2.amazonaws.com/mainnet

dumpExporter:
  enabled: true
  suspend: true
  s3:
    bucket: 673156464838-mina-archive-node-backups
