apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kyc-management-app.fullname" . }}-dex
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kyc-management-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kyc-management-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kyc-management-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kyc-management-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: dex
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.kycDex.image.repository }}:{{ .Values.kycDex.image.tag }}"
          imagePullPolicy: {{ .Values.kycDex.image.pullPolicy }}
          command:
            - /usr/local/bin/dex
            - serve
            - /etc/dex/config.yaml
          env:
          {{- with .Values.kycDex.envVars }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: dex
              containerPort: {{ .Values.kycDex.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.kycDex.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.kycDex.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.kycDex.resources | nindent 12 }}
          volumeMounts:
            - name: dex
              mountPath: "/etc/dex"
              readOnly: true
          {{- with .Values.kycDex.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: dex
          secret:
            secretName: {{ include "kyc-management-app.fullname" . }}-dex
            optional: false
            items:
              - key: dex.yaml
                path: config.yaml
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
