{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kyc-management-app.fullname" . }}
  labels:
    {{- include "kyc-management-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "kyc-management-app.fullname" . }}-dex
                port:
                  number: {{ .Values.kycDex.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kyc-management-app.fullname" . }}-api
                port:
                  number: {{ .Values.kycApi.port }}
{{- end }}
