apiVersion: v1
kind: Service
metadata:
  name: {{ include "kyc-management-app.fullname" . }}
  labels:
    {{- include "kyc-management-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.kycManagementApp.app.port }}
      targetPort: http
      protocol: TCP
      name: app
    - port: {{ .Values.kycManagementApp.dex.port }}
      targetPort: http
      protocol: TCP
      name: dex
  selector:
    {{- include "kyc-management-app.selectorLabels" . | nindent 4 }}
