# Default values for pod-rotation-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- The repository of the image
  repository: 673156464838.dkr.ecr.us-west-2.amazonaws.com/github-actions-runner
  # -- The pullPolicy used when pulling the image
  pullPolicy: IfNotPresent
  # -- The tag of the image.
  tag: "default-2023.09.26"

# -- The secrets used to pull the image
imagePullSecrets: []
# -- The release name override
nameOverride: ""
# -- The full release name override
fullnameOverride: ""

serviceAccount:
  # -- Create a service account
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use
  name: ""

# -- Annotations to add to deployments
podAnnotations: {}

# -- Annotations to add to the pods
podLabels: {}

# -- The Pod Regex Pattern
podRegexPattern: ".*"

# -- The Pod Rotation Schedule
schedule: "0 */6 * * *"

# -- The restart policy
restartPolicy: "OnFailure"

# -- The Pod Security Context
podSecurityContext: {}
# -- The Security Context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Resources
resources:
  # -- The resources limits for the pod-rotation-controller container
  limits: {}
  # -- The resources requests for the pod-rotation-controller container
  requests: {}

# -- Node Selector
nodeSelector: {}

# -- Tolerations
tolerations: []

# -- Affinity
affinity: {}
