# Default values for node-stats-collector.

# -- The number of replicas
replicaCount: 1

image:
  # -- The repository of the image
  repository: 673156464838.dkr.ecr.us-west-2.amazonaws.com/node-stats-collector
  # -- The pullPolicy used when pulling the image
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "2023.09"

# -- The name override
nameOverride: ""
# -- The full name override
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  name: ""

# -- Annotations to add to the pods
podAnnotations: {}

# -- The Pod Security Context
podSecurityContext: {}
  # fsGroup: 2000

# -- The Security Context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Extra environment variables
extraEnvVars: {}
  # - name: FOO
  #   value: FOO
  # - name: BAR
  #   valueFrom:
  #     secretKeyRef:
  #       name: mySecret
  #       key: bar

service:
  # -- The service type
  type: ClusterIP
  # -- The service port
  port: 8080

nodestats:
  # -- Endpoint to collect node stats
  endpoint: ""
  # -- Index to store node stats
  index: "node-stats-errors"
  metrics:
    # -- Enable Metrics collection
    enabled: true

ingress:
  # -- Whether to create an Ingress
  enabled: false
  # -- The Ingress Class Name to use
  className: ""
  # -- The Ingress Annotations
  annotations: {}
  # -- The Ingress Hosts
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# -- Resource limitations for the pods
resources: {}

autoscaling:
  # -- Enable autoscaling
  enabled: false
  # -- The minimum number of replicas
  minReplicas: 1
  # -- The maximum number of replicas
  maxReplicas: 100
  # -- The target CPU utilization percentage
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Node selector
nodeSelector: {}
# -- Tolerations
tolerations: []
# -- Affinity rules
affinity: {}
